"""Add Staff and Payroll fields

Revision ID: 30b0ab978a47
Revises: 5a4ade3452f6
Create Date: 2026-07-20 10:46:28.242727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b0ab978a47'
down_revision: Union[str, None] = '5a4ade3452f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_payments', sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('salary_payments', sa.Column('advance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('salary_payments', sa.Column('deductions', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('staff', sa.Column('email', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('qualification', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'address')
    op.drop_column('staff', 'qualification')
    op.drop_column('staff', 'email')
    op.drop_column('salary_payments', 'deductions')
    op.drop_column('salary_payments', 'advance')
    op.drop_column('salary_payments', 'bonus')
    # ### end Alembic commands ###
