"""Add is_discountable to FeeHead

Revision ID: 5a4ade3452f6
Revises: ae3c90fe0edd
Create Date: 2026-07-20 10:40:05.138756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4ade3452f6'
down_revision: Union[str, None] = 'ae3c90fe0edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_heads', sa.Column('is_discountable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_heads', 'is_discountable')
    # ### end Alembic commands ###
