"""Initial schema

Revision ID: 81ba6d1355e0
Revises: 
Create Date: 2026-06-19 10:01:00.282456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ba6d1355e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'2026-2027'"))
        batch_op.drop_constraint(batch_op.f('_class_section_uc'), type_='unique')
        batch_op.create_unique_constraint('_class_branch_year_uc', ['name', 'academic_year', 'branch_id'])
        batch_op.create_foreign_key(batch_op.f('fk_classes_branch_id_branches'), 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.alter_column('primary_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_parents_parent_contact_number'), ['parent_contact_number'], unique=True)

    with op.batch_alter_table('student_fee_mapping', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_student_fee_mapping_student_id'), ['student_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('blood_group',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_students_admission_number'), ['admission_number'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('uq_students_roll_no'), ['roll_no'])
        batch_op.create_foreign_key(batch_op.f('fk_students_branch_id_branches'), 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_users_role_id_roles'), 'roles', ['role_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_branch_id_branches'), 'branches', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_branch_id_branches'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_role_id_roles'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_students_branch_id_branches'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_students_roll_no'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_students_admission_number'))
        batch_op.alter_column('blood_group',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('parent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('student_fee_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_student_fee_mapping_student_id'), type_='unique')

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parents_parent_contact_number'))
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('primary_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classes_branch_id_branches'), type_='foreignkey')
        batch_op.drop_constraint('_class_branch_year_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_class_section_uc'), ['name', 'section'])
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'2026-2027'"))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
