"""Add branch_id to models

Revision ID: 95c766575fd1
Revises: d7a7a3e3793e
Create Date: 2026-07-20 10:31:38.144754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c766575fd1'
down_revision: Union[str, None] = 'd7a7a3e3793e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('branch_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'broadcasts', 'branches', ['branch_id'], ['id'])
    op.add_column('general_ledger', sa.Column('branch_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'general_ledger', 'branches', ['branch_id'], ['id'])
    op.add_column('parents', sa.Column('branch_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'parents', 'branches', ['branch_id'], ['id'])
    op.add_column('payment_history', sa.Column('branch_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'payment_history', 'branches', ['branch_id'], ['id'])
    op.add_column('staff', sa.Column('branch_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'staff', 'branches', ['branch_id'], ['id'])
    op.add_column('students', sa.Column('branch_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'students', 'branches', ['branch_id'], ['id'])
    op.add_column('users', sa.Column('branch_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'branch_id')
    op.drop_column('students', 'branch_id')
    op.drop_column('staff', 'branch_id')
    op.drop_column('payment_history', 'branch_id')
    op.drop_column('parents', 'branch_id')
    op.drop_column('general_ledger', 'branch_id')
    op.drop_column('broadcasts', 'branch_id')
    # ### end Alembic commands ###
