"""Dynamic FeeHead Schema

Revision ID: ae3c90fe0edd
Revises: 95c766575fd1
Create Date: 2026-07-20 10:37:23.812399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3c90fe0edd'
down_revision: Union[str, None] = '95c766575fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_heads', sa.Column('description', sa.String(), nullable=True))
    op.add_column('fee_heads', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_heads', 'is_active')
    op.drop_column('fee_heads', 'description')
    # ### end Alembic commands ###
